# Generated by Django 5.1.1 on 2024-10-13 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usermaster_company_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermaster',
            name='otp',
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='is_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 13, 15, 26, 29, 147635)),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='is_updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 13, 15, 26, 29, 147635)),
        ),
    ]
